name: Android CI with GitHub Actions

on:
  push:
    branches: [ master, workflow-init ]
  pull_request:
    branches: [ master, workflow-init ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world"

